# Generated by Django 5.0.4 on 2024-04-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_amenity_room_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='image',
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='rooms.amenity'),
        ),
    ]
