# Generated by Django 5.0.4 on 2024-04-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_amenity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='city',
        ),
    ]
