# Generated by Django 5.0.4 on 2024-04-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_city_location_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.amenity'),
        ),
    ]
