# Generated by Django 4.2.11 on 2024-07-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_room_image2_room_image3_room_image4_room_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='google_map_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps URL'),
        ),
    ]
