# Generated by Django 4.2.11 on 2024-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_room_google_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='google_map_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Google Maps URL'),
        ),
    ]
