# Generated by Django 5.0.4 on 2024-04-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_first_name_user_is_vendor_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_expiry', models.DateTimeField()),
            ],
        ),
    ]
