# Generated by Django 5.0.4 on 2024-04-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_otp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
    ]
