# Generated by Django 5.0.4 on 2024-04-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_otp_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPEmails',
            new_name='temporay',
        ),
    ]
