# Generated by Django 5.0.4 on 2024-04-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_otpemails_temporay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporay',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
