# Generated by Django 4.2.11 on 2024-04-08 00:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_expiry',
            field=models.DateTimeField(default=accounts.models.default_expiry),
        ),
    ]
