# Generated by Django 5.0.4 on 2024-04-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_otp_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
