# Generated by Django 5.0.4 on 2024-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_otp_phone_number_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_profile_photo'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
