# Generated by Django 5.0.4 on 2024-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_image_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='user_profile_photo'),
        ),
    ]
