# Generated by Django 5.0.4 on 2024-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_guest',
            field=models.IntegerField(default=0),
        ),
    ]
