# Generated by Django 5.0.4 on 2024-04-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_booking_total_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_guest',
            field=models.IntegerField(),
        ),
    ]
