# Generated by Django 5.0.4 on 2024-05-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(default=8113986544, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='saeed', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='nm', max_length=100),
            preserve_default=False,
        ),
    ]
