# Generated by Django 4.2.11 on 2024-08-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='user_profile_photo'),
        ),
    ]
