# Generated by Django 4.2.11 on 2024-07-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='button_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_bg_color',
            field=models.CharField(default='#3c3737', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
