# Generated by Django 4.2.11 on 2024-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_remove_banner_button_url_banner_button_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='button_bg_color',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text_color',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_content',
            field=models.CharField(default='', max_length=100),
        ),
    ]
