# Generated by Django 4.2.11 on 2024-08-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_remove_banner_button_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
