# Generated by Django 4.2.11 on 2024-08-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_alter_banner_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image_url',
            new_name='image',
        ),
    ]
